/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

type ConditionObservation struct {
}

type ConditionParameters struct {

	// +kubebuilder:validation:Optional
	Operation *string `json:"operation,omitempty" tf:"operation"`

	// +kubebuilder:validation:Optional
	Property *string `json:"property,omitempty" tf:"property"`

	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value"`
}

type MediaAssetFilterObservation struct {
}

type MediaAssetFilterParameters struct {

	// +kubebuilder:validation:Required
	AssetID string `json:"assetId" tf:"asset_id"`

	// +kubebuilder:validation:Optional
	FirstQualityBitrate *int64 `json:"firstQualityBitrate,omitempty" tf:"first_quality_bitrate"`

	// +kubebuilder:validation:Required
	Name string `json:"name" tf:"name"`

	// +kubebuilder:validation:Optional
	PresentationTimeRange []PresentationTimeRangeParameters `json:"presentationTimeRange,omitempty" tf:"presentation_time_range"`

	// +kubebuilder:validation:Optional
	TrackSelection []TrackSelectionParameters `json:"trackSelection,omitempty" tf:"track_selection"`
}

type PresentationTimeRangeObservation struct {
}

type PresentationTimeRangeParameters struct {

	// +kubebuilder:validation:Optional
	EndInUnits *int64 `json:"endInUnits,omitempty" tf:"end_in_units"`

	// +kubebuilder:validation:Optional
	ForceEnd *bool `json:"forceEnd,omitempty" tf:"force_end"`

	// +kubebuilder:validation:Optional
	LiveBackoffInUnits *int64 `json:"liveBackoffInUnits,omitempty" tf:"live_backoff_in_units"`

	// +kubebuilder:validation:Optional
	PresentationWindowInUnits *int64 `json:"presentationWindowInUnits,omitempty" tf:"presentation_window_in_units"`

	// +kubebuilder:validation:Optional
	StartInUnits *int64 `json:"startInUnits,omitempty" tf:"start_in_units"`

	// +kubebuilder:validation:Optional
	UnitTimescaleInMiliseconds *int64 `json:"unitTimescaleInMiliseconds,omitempty" tf:"unit_timescale_in_miliseconds"`
}

type TrackSelectionObservation struct {
}

type TrackSelectionParameters struct {

	// +kubebuilder:validation:Required
	Condition []ConditionParameters `json:"condition" tf:"condition"`
}

// MediaAssetFilterSpec defines the desired state of MediaAssetFilter
type MediaAssetFilterSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       MediaAssetFilterParameters `json:"forProvider"`
}

// MediaAssetFilterStatus defines the observed state of MediaAssetFilter.
type MediaAssetFilterStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          MediaAssetFilterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// MediaAssetFilter is the Schema for the MediaAssetFilters API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azure}
type MediaAssetFilter struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              MediaAssetFilterSpec   `json:"spec"`
	Status            MediaAssetFilterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MediaAssetFilterList contains a list of MediaAssetFilters
type MediaAssetFilterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MediaAssetFilter `json:"items"`
}

// Repository type metadata.
var (
	MediaAssetFilterKind             = "MediaAssetFilter"
	MediaAssetFilterGroupKind        = schema.GroupKind{Group: Group, Kind: MediaAssetFilterKind}.String()
	MediaAssetFilterKindAPIVersion   = MediaAssetFilterKind + "." + GroupVersion.String()
	MediaAssetFilterGroupVersionKind = GroupVersion.WithKind(MediaAssetFilterKind)
)

func init() {
	SchemeBuilder.Register(&MediaAssetFilter{}, &MediaAssetFilterList{})
}
