/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

type ApiManagementBackendObservation struct {
}

type ApiManagementBackendParameters struct {

	// +kubebuilder:validation:Required
	APIManagementName string `json:"apiManagementName" tf:"api_management_name"`

	// +kubebuilder:validation:Optional
	Credentials []CredentialsParameters `json:"credentials,omitempty" tf:"credentials"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description"`

	// +kubebuilder:validation:Required
	Name string `json:"name" tf:"name"`

	// +kubebuilder:validation:Required
	Protocol string `json:"protocol" tf:"protocol"`

	// +kubebuilder:validation:Optional
	Proxy []ApiManagementBackendProxyParameters `json:"proxy,omitempty" tf:"proxy"`

	// +kubebuilder:validation:Required
	ResourceGroupName string `json:"resourceGroupName" tf:"resource_group_name"`

	// +kubebuilder:validation:Optional
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id"`

	// +kubebuilder:validation:Optional
	ServiceFabricCluster []ServiceFabricClusterParameters `json:"serviceFabricCluster,omitempty" tf:"service_fabric_cluster"`

	// +kubebuilder:validation:Optional
	TLS []TLSParameters `json:"tls,omitempty" tf:"tls"`

	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title"`

	// +kubebuilder:validation:Required
	URL string `json:"url" tf:"url"`
}

type ApiManagementBackendProxyObservation struct {
}

type ApiManagementBackendProxyParameters struct {

	// +kubebuilder:validation:Optional
	Password *string `json:"password,omitempty" tf:"password"`

	// +kubebuilder:validation:Required
	URL string `json:"url" tf:"url"`

	// +kubebuilder:validation:Required
	Username string `json:"username" tf:"username"`
}

type AuthorizationObservation struct {
}

type AuthorizationParameters struct {

	// +kubebuilder:validation:Optional
	Parameter *string `json:"parameter,omitempty" tf:"parameter"`

	// +kubebuilder:validation:Optional
	Scheme *string `json:"scheme,omitempty" tf:"scheme"`
}

type CredentialsObservation struct {
}

type CredentialsParameters struct {

	// +kubebuilder:validation:Optional
	Authorization []AuthorizationParameters `json:"authorization,omitempty" tf:"authorization"`

	// +kubebuilder:validation:Optional
	Certificate []string `json:"certificate,omitempty" tf:"certificate"`

	// +kubebuilder:validation:Optional
	Header map[string]string `json:"header,omitempty" tf:"header"`

	// +kubebuilder:validation:Optional
	Query map[string]string `json:"query,omitempty" tf:"query"`
}

type ServerX509NameObservation struct {
}

type ServerX509NameParameters struct {

	// +kubebuilder:validation:Required
	IssuerCertificateThumbprint string `json:"issuerCertificateThumbprint" tf:"issuer_certificate_thumbprint"`

	// +kubebuilder:validation:Required
	Name string `json:"name" tf:"name"`
}

type ServiceFabricClusterObservation struct {
}

type ServiceFabricClusterParameters struct {

	// +kubebuilder:validation:Optional
	ClientCertificateID *string `json:"clientCertificateId,omitempty" tf:"client_certificate_id"`

	// +kubebuilder:validation:Optional
	ClientCertificateThumbprint *string `json:"clientCertificateThumbprint,omitempty" tf:"client_certificate_thumbprint"`

	// +kubebuilder:validation:Required
	ManagementEndpoints []string `json:"managementEndpoints" tf:"management_endpoints"`

	// +kubebuilder:validation:Required
	MaxPartitionResolutionRetries int64 `json:"maxPartitionResolutionRetries" tf:"max_partition_resolution_retries"`

	// +kubebuilder:validation:Optional
	ServerCertificateThumbprints []string `json:"serverCertificateThumbprints,omitempty" tf:"server_certificate_thumbprints"`

	// +kubebuilder:validation:Optional
	ServerX509Name []ServerX509NameParameters `json:"serverX509Name,omitempty" tf:"server_x509_name"`
}

type TLSObservation struct {
}

type TLSParameters struct {

	// +kubebuilder:validation:Optional
	ValidateCertificateChain *bool `json:"validateCertificateChain,omitempty" tf:"validate_certificate_chain"`

	// +kubebuilder:validation:Optional
	ValidateCertificateName *bool `json:"validateCertificateName,omitempty" tf:"validate_certificate_name"`
}

// ApiManagementBackendSpec defines the desired state of ApiManagementBackend
type ApiManagementBackendSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       ApiManagementBackendParameters `json:"forProvider"`
}

// ApiManagementBackendStatus defines the observed state of ApiManagementBackend.
type ApiManagementBackendStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          ApiManagementBackendObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ApiManagementBackend is the Schema for the ApiManagementBackends API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azure}
type ApiManagementBackend struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ApiManagementBackendSpec   `json:"spec"`
	Status            ApiManagementBackendStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApiManagementBackendList contains a list of ApiManagementBackends
type ApiManagementBackendList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ApiManagementBackend `json:"items"`
}

// Repository type metadata.
var (
	ApiManagementBackendKind             = "ApiManagementBackend"
	ApiManagementBackendGroupKind        = schema.GroupKind{Group: Group, Kind: ApiManagementBackendKind}.String()
	ApiManagementBackendKindAPIVersion   = ApiManagementBackendKind + "." + GroupVersion.String()
	ApiManagementBackendGroupVersionKind = GroupVersion.WithKind(ApiManagementBackendKind)
)

func init() {
	SchemeBuilder.Register(&ApiManagementBackend{}, &ApiManagementBackendList{})
}
