/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

type DataFactoryDatasetParquetAzureBlobStorageLocationObservation struct {
}

type DataFactoryDatasetParquetAzureBlobStorageLocationParameters struct {

	// +kubebuilder:validation:Required
	Container string `json:"container" tf:"container"`

	// +kubebuilder:validation:Optional
	DynamicFilenameEnabled *bool `json:"dynamicFilenameEnabled,omitempty" tf:"dynamic_filename_enabled"`

	// +kubebuilder:validation:Optional
	DynamicPathEnabled *bool `json:"dynamicPathEnabled,omitempty" tf:"dynamic_path_enabled"`

	// +kubebuilder:validation:Optional
	Filename *string `json:"filename,omitempty" tf:"filename"`

	// +kubebuilder:validation:Required
	Path string `json:"path" tf:"path"`
}

type DataFactoryDatasetParquetHTTPServerLocationObservation struct {
}

type DataFactoryDatasetParquetHTTPServerLocationParameters struct {

	// +kubebuilder:validation:Optional
	DynamicFilenameEnabled *bool `json:"dynamicFilenameEnabled,omitempty" tf:"dynamic_filename_enabled"`

	// +kubebuilder:validation:Optional
	DynamicPathEnabled *bool `json:"dynamicPathEnabled,omitempty" tf:"dynamic_path_enabled"`

	// +kubebuilder:validation:Required
	Filename string `json:"filename" tf:"filename"`

	// +kubebuilder:validation:Required
	Path string `json:"path" tf:"path"`

	// +kubebuilder:validation:Required
	RelativeURL string `json:"relativeUrl" tf:"relative_url"`
}

type DataFactoryDatasetParquetObservation struct {
}

type DataFactoryDatasetParquetParameters struct {

	// +kubebuilder:validation:Optional
	AdditionalProperties map[string]string `json:"additionalProperties,omitempty" tf:"additional_properties"`

	// +kubebuilder:validation:Optional
	Annotations []string `json:"annotations,omitempty" tf:"annotations"`

	// +kubebuilder:validation:Optional
	AzureBlobStorageLocation []DataFactoryDatasetParquetAzureBlobStorageLocationParameters `json:"azureBlobStorageLocation,omitempty" tf:"azure_blob_storage_location"`

	// +kubebuilder:validation:Optional
	CompressionCodec *string `json:"compressionCodec,omitempty" tf:"compression_codec"`

	// +kubebuilder:validation:Optional
	CompressionLevel *string `json:"compressionLevel,omitempty" tf:"compression_level"`

	// +kubebuilder:validation:Required
	DataFactoryName string `json:"dataFactoryName" tf:"data_factory_name"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description"`

	// +kubebuilder:validation:Optional
	Folder *string `json:"folder,omitempty" tf:"folder"`

	// +kubebuilder:validation:Optional
	HTTPServerLocation []DataFactoryDatasetParquetHTTPServerLocationParameters `json:"httpServerLocation,omitempty" tf:"http_server_location"`

	// +kubebuilder:validation:Required
	LinkedServiceName string `json:"linkedServiceName" tf:"linked_service_name"`

	// +kubebuilder:validation:Required
	Name string `json:"name" tf:"name"`

	// +kubebuilder:validation:Optional
	Parameters map[string]string `json:"parameters,omitempty" tf:"parameters"`

	// +kubebuilder:validation:Required
	ResourceGroupName string `json:"resourceGroupName" tf:"resource_group_name"`

	// +kubebuilder:validation:Optional
	SchemaColumn []DataFactoryDatasetParquetSchemaColumnParameters `json:"schemaColumn,omitempty" tf:"schema_column"`
}

type DataFactoryDatasetParquetSchemaColumnObservation struct {
}

type DataFactoryDatasetParquetSchemaColumnParameters struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description"`

	// +kubebuilder:validation:Required
	Name string `json:"name" tf:"name"`

	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type"`
}

// DataFactoryDatasetParquetSpec defines the desired state of DataFactoryDatasetParquet
type DataFactoryDatasetParquetSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DataFactoryDatasetParquetParameters `json:"forProvider"`
}

// DataFactoryDatasetParquetStatus defines the observed state of DataFactoryDatasetParquet.
type DataFactoryDatasetParquetStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DataFactoryDatasetParquetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// DataFactoryDatasetParquet is the Schema for the DataFactoryDatasetParquets API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azure}
type DataFactoryDatasetParquet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DataFactoryDatasetParquetSpec   `json:"spec"`
	Status            DataFactoryDatasetParquetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DataFactoryDatasetParquetList contains a list of DataFactoryDatasetParquets
type DataFactoryDatasetParquetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DataFactoryDatasetParquet `json:"items"`
}

// Repository type metadata.
var (
	DataFactoryDatasetParquetKind             = "DataFactoryDatasetParquet"
	DataFactoryDatasetParquetGroupKind        = schema.GroupKind{Group: Group, Kind: DataFactoryDatasetParquetKind}.String()
	DataFactoryDatasetParquetKindAPIVersion   = DataFactoryDatasetParquetKind + "." + GroupVersion.String()
	DataFactoryDatasetParquetGroupVersionKind = GroupVersion.WithKind(DataFactoryDatasetParquetKind)
)

func init() {
	SchemeBuilder.Register(&DataFactoryDatasetParquet{}, &DataFactoryDatasetParquetList{})
}
